SELECT TOP (1000) [GID]
      ,[EnterpriseID]
      ,[MouldCode]
      ,[MouldName]
      ,[BeginDate]
      ,[EndDate]
      ,[Status]
      ,[StatusTime]
      ,[Remark]
      ,[LastOp]
      ,[LastModify]
      ,[MouldType]
  FROM [NCW_xurf].[dbo].[P_FoodMould_M]
  WHERE EnterpriseID = '90367984' AND MouldName = '掃碼點餐(仿晨間)'