SELECT TOP (1000) [GID]
      ,[EnterpriseID]
      ,[KindID]
      ,[FoodID]
      ,[MaxCount]
      ,[Group]
      ,[ShopID]
      ,[LastOP]
      ,[LastModify]
      ,[EntKindNo]
      ,[IsDeskOrder]
      ,[IsPadOrder]
      ,[KindName]
  FROM [NCW_xurf].[dbo].[P_FoodEntKind]