SELECT TOP (1000) [GID]
      ,[EnterpriseID]
      ,[ID]
      ,[KindID]
      ,[Owner]
      ,[Name]
      ,[Price]
      ,[X]
      ,[Y]
      ,[Style]
      ,[Lock]
      ,[Page]
      ,[ShopID]
      ,[LastOP]
      ,[LastModify]
      ,[AddKindID]
      ,[IsDeskOrder]
      ,[IsPadOrder]
      ,[IsAppOrder]
      ,[SN]
      ,[FoodID]
      ,[MGID]
  FROM [NCW_xurf].[dbo].[P_FoodAdd]
  WHERE EnterpriseID = 'xurf' AND Owner = 'la0341774'