SELECT TOP (1000) [GID]
      ,[Name]
      ,[DefaultValue]
      ,[Type]
      ,[Desc]
      ,[CodePage]
      ,[IsUser]
      ,[AppSetting_M_GID]
      ,[ChnName]
      ,[ValueExpress]
      ,[Sn]
      ,[Data]
      ,[TwName]
      ,[EnName]
      ,[LastOP]
      ,[LastModify]
  FROM [NCW_xurf].[dbo].[S_AppSetting_D]
  WHERE AppSetting_M_GID = '30a6d2f5-b48e-4c59-be95-552a7488d368'