SELECT TOP (1000) [EnterpriseID]
      ,[GID]
      ,[NO]
      ,[Name]
      ,[AreaID]
      ,[StateID]
      ,[StartTime]
      ,[MaxTime]
      ,[Cost]
      ,[OrderCount]
      ,[Operator]
      ,[Style]
      ,[Image]
      ,[X]
      ,[Y]
      ,[SeatNum]
      ,[ManCount]
      ,[WomanCount]
      ,[ChildCount]
      ,[BabyCount]
      ,[ShopID]
      ,[LastModify]
      ,[LastOP]
      ,[LastState]
      ,[AutoDesk]
  FROM [NCW_xurf].[dbo].[T_Desk]
  WHERE EnterPriseID = '90367984' AND ShopID = 'A01'