SELECT TOP (1000) [GID]
      ,[LastOP]
      ,[LastModify]
      ,[EnterPriseID]
      ,[TicketTypeCode]
      ,[TicketTypeName]
      ,[TicketFlag]
      ,[TicketPrice]
      ,[TicketDiscount]
      ,[FoodMaxMoney]
      ,[TicketNumCount]
      ,[CheckKindID]
      ,[ValidType]
      ,[ValidDays]
      ,[ExpiredDate]
      ,[Remark]
      ,[MustInputTicketNO]
      ,[AutoGenTicketNO]
      ,[TicketNoPrefix]
      ,[TicketCurrSeri]
      ,[OrderMinMoney]
      ,[UseMaxCount]
      ,[NeedRule]
      ,[PicUrl]
      ,[TicketTypeNameEn]
  FROM [NCW_xurf].[dbo].[VIP_TicketType]
  WHERE EnterPriseID = '90367984'