SELECT TOP (1000) [GID]
      ,[EnterPriseID]
      ,[TicketInfoID]
      ,[TradeNum]
      ,[MemberNO]
      ,[CardNO]
      ,[CardID]
      ,[TradeRuleCode]
      ,[TicketTypeCode]
      ,[StartTicketCount]
      ,[TicketCount]
      ,[TicketFactPrice]
      ,[TicketPrice]
      ,[TicketTotal]
      ,[TicketFactTotal]
      ,[StartTicketTotal]
      ,[StartTicketFactTotal]
      ,[TicketBgnNO]
      ,[TicketEndNO]
      ,[TicketExpiredDate]
      ,[GenTradetime]
      ,[Operator]
      ,[Remark]
      ,[MAC]
      ,[LastModify]
      ,[CardTradeNum]
      ,[CXTradeNum]
      ,[GenReason]
      ,[QrCode]
      ,[QrCodeTime]
      ,[PublishGID]
      ,[DrawGID]
      ,[PutGID]
      ,[CaceldGID]
      ,[ExtendGID]
      ,[TIfrom_GID]
      ,[TIto_GID]
  FROM [NCW_xurf].[dbo].[VIP_TicketInfo]
  WHERE EnterPriseID = '90367984'
  and GenTradetime > '2025-05-14'