SELECT TOP (1000) [GID]
      ,[EnterPriseID]
      ,[CardTypeCode1]
      ,[CardTypeCode2]
      ,[CumulativeSales]
      ,[Days]
      ,[CreateOP]
      ,[CreateDate]
      ,[LastOP]
      ,[LastModify]
      ,[Remarks]
      ,[CumulativeBalance]
      ,[TradeRuleCode]
  FROM [NCW_xurf].[dbo].[VIP_CardUpgradeRules]