SELECT TOP (1000) [GID]
      ,[EnterPriseID]
      ,[CardTypeCode]
      ,[CardTypeName]
      ,[CardDisCount]
      ,[ExpiredDate]
      ,[ValidDays]
      ,[ValidType]
      ,[NumCount]
      ,[MoneyBegin]
      ,[CardDeposit]
      ,[BalanceLimit]
      ,[IsSingleUse]
      ,[Remark]
      ,[PointMoneyRate]
      ,[Discount]
      ,[ActiveAllShop]
      ,[CardUseType]
      ,[MakeCardAutoActive]
      ,[LastOP]
      ,[LastModify]
      ,[CardFacePhoto]
      ,[CardTypeLevel]
  FROM [NCW_xurf].[dbo].[VIP_CardType]