SELECT TOP (1000) [GID]
      ,[LastOP]
      ,[LastModify]
      ,[EnterPriseID]
      ,[Pro_Code]
      ,[Pro_Name]
      ,[Pro_Mathods]
      ,[Pro_start]
      ,[Pro_end]
      ,[Remark]
      ,[status]
      ,[ShopID]
      ,[ProposerOp]
      ,[ProposerDate]
      ,[StatusPersonal]
      ,[StatusTime]
      ,[StatusToShop]
      ,[TicketTypeCode]
  FROM [NCW_xurf].[dbo].[VIP_ProMotion]
  WHERE EnterPriseID = '90367984'